# Generated by Django 5.1.3 on 2024-12-23 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('bank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=155)),
                ('bank_branch', models.CharField(max_length=155)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=55)),
                ('bank_account_holder', models.CharField(blank=True, max_length=155, null=True)),
                ('bank_initial_amount', models.CharField(blank=True, max_length=155, null=True)),
                ('bank_open_closed', models.BooleanField(default=1)),
                ('company_bank_account', models.BooleanField(default=0)),
            ],
            options={
                'db_table': 'Bank_Details',
            },
        ),
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_contact_number', models.CharField(max_length=15)),
                ('company_owner_name', models.CharField(max_length=155)),
                ('company_owner_contact', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
                ('company_logo_icon', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'db_table': 'Company_Details',
            },
        ),
        migrations.CreateModel(
            name='Document_Types',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Document_Types',
            },
        ),
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gujarati', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'language',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language_type', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], max_length=155)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Machine_Types',
            fields=[
                ('machine_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Machine_Types',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_Types',
            fields=[
                ('maintenance_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Maintenance_Types',
            },
        ),
        migrations.CreateModel(
            name='Material_Types',
            fields=[
                ('material_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Material_Types',
            },
        ),
        migrations.CreateModel(
            name='Pay_Types',
            fields=[
                ('pay_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Pay_Types',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=155)),
                ('person_contact_number', models.CharField(max_length=15)),
                ('person_register_date', models.DateField(auto_now_add=True)),
                ('person_status', models.BooleanField(default=1)),
                ('person_address', models.TextField(blank=True, null=True)),
                ('person_other_details', models.TextField(blank=True, null=True)),
                ('person_business_job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_business_job_company_num', models.CharField(blank=True, max_length=15, null=True)),
                ('person_business_job_address', models.TextField(blank=True, null=True)),
                ('person_gst', models.CharField(blank=True, max_length=155, null=True)),
                ('person_types_for_project', models.CharField(blank=True, choices=[('Worker', 'Worker'), ('Project', 'Project'), ('Material', 'Material'), ('Machine', 'Machine'), ('Other', 'Other')], max_length=155, null=True)),
                ('person_salary', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Person_Type',
            fields=[
                ('person_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Person_Type',
            },
        ),
        migrations.CreateModel(
            name='Project_Types',
            fields=[
                ('project_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_type_name', models.CharField(max_length=155)),
                ('project_type_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Project_Types',
            },
        ),
        migrations.CreateModel(
            name='Settingsss',
            fields=[
                ('settings_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('settings_field_name', models.CharField(max_length=200)),
                ('settings_field_value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Settingsss',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=155)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=55)),
                ('user_otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Work_Types',
            fields=[
                ('work_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_type_name', models.CharField(max_length=155)),
                ('work_type_details', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Work_Types',
            },
        ),
        migrations.CreateModel(
            name='bank_cash',
            fields=[
                ('bank_cash_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('credit_debit', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('details', models.TextField(blank=True, null=True)),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.bank_details')),
            ],
            options={
                'db_table': 'bank_cash',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=155)),
                ('document_date', models.DateField(auto_now_add=True)),
                ('document_unique_code', models.CharField(max_length=155, unique=True)),
                ('document_file', models.FileField(upload_to='uploads/')),
                ('document_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.document_types')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
            ],
            options={
                'db_table': 'Documents',
            },
        ),
        migrations.CreateModel(
            name='Document_Dates',
            fields=[
                ('dd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dd_date_name', models.CharField(max_length=200)),
                ('dd_date', models.DateField(auto_now_add=True)),
                ('dd_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.documents')),
            ],
            options={
                'db_table': 'Document_Dates',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=155)),
                ('machine_number_plate', models.CharField(max_length=55)),
                ('machine_register_date', models.DateField()),
                ('machine_own', models.CharField(choices=[('Company', 'Company'), ('Rented_fixedprice', 'Rented_fixedprice'), ('Rented_variableprice', 'Rented_variableprice')], max_length=55)),
                ('machine_condition', models.CharField(blank=True, choices=[('New', 'New'), ('Second_hand', 'Second_hand')], max_length=55, null=True)),
                ('machine_working', models.BooleanField(default=1)),
                ('machine_details', models.TextField(blank=True, null=True)),
                ('machine_rented_work_price', models.CharField(blank=True, max_length=150, null=True)),
                ('machine_buy_price', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_buy_date', models.DateField(blank=True, null=True)),
                ('machine_sold_price', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_sold_out_date', models.DateField(blank=True, null=True)),
                ('machine_other_details', models.TextField(blank=True, null=True)),
                ('machine_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machine_types')),
                ('machine_owner_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('machine_rented_work_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_status', models.BooleanField(default=1)),
                ('material_buy_date', models.DateField(blank=True, null=True)),
                ('material_buy_location', models.TextField(blank=True, null=True)),
                ('material_work_no', models.CharField(max_length=100)),
                ('material_price', models.CharField(max_length=250)),
                ('material_total_price', models.CharField(max_length=250)),
                ('material_is_agent', models.BooleanField(default=0)),
                ('material_agent_name', models.CharField(max_length=100)),
                ('material_agent_contact', models.CharField(max_length=100)),
                ('material_agent_price_choice', models.CharField(max_length=50)),
                ('material_agent_percentage', models.CharField(max_length=10)),
                ('material_agent_amount', models.CharField(max_length=200)),
                ('material_final_amount', models.CharField(max_length=200)),
                ('material_details', models.TextField(blank=True, null=True)),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_types')),
                ('material_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('material_work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.AddField(
            model_name='bank_details',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person'),
        ),
        migrations.AddField(
            model_name='person',
            name='person_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=155)),
                ('project_amount', models.CharField(blank=True, max_length=55, null=True)),
                ('project_location', models.CharField(max_length=155)),
                ('project_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Closed', 'Closed'), ('Taken', 'Taken')], max_length=55)),
                ('project_start_date', models.DateField(auto_now_add=True, null=True)),
                ('project_end_date', models.DateField(auto_now_add=True, null=True)),
                ('project_cgst', models.CharField(blank=True, max_length=55, null=True)),
                ('project_sgst', models.CharField(blank=True, max_length=55, null=True)),
                ('project_tax', models.CharField(blank=True, max_length=55, null=True)),
                ('project_discount', models.CharField(blank=True, max_length=55, null=True)),
                ('project_agent', models.BooleanField(default=0)),
                ('project_agent_type', models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=155, null=True)),
                ('project_agent_percentage', models.CharField(blank=True, max_length=155, null=True)),
                ('project_agent_fixed_amount', models.CharField(blank=True, max_length=155, null=True)),
                ('project_final_amount', models.CharField(blank=True, max_length=155, null=True)),
                ('project_agent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_name', to='pinak_app.person')),
                ('project_owner_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='pinak_app.person')),
                ('project_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_types')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Money_Debit_Credit',
            fields=[
                ('money_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('money_payment_mode', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=155)),
                ('money_amount', models.CharField(max_length=155)),
                ('money_date', models.DateField()),
                ('money_sender_cheque_no', models.CharField(blank=True, max_length=155, null=True)),
                ('money_payment_details', models.TextField(blank=True, null=True)),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('receiver_bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_bank_id', to='pinak_app.bank_details')),
                ('sender_bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank_id', to='pinak_app.bank_details')),
                ('pay_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.pay_types')),
                ('receiver_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_person_id', to='pinak_app.person')),
                ('sender_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_person_id', to='pinak_app.person')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Money_Debit_Credit',
            },
        ),
        migrations.CreateModel(
            name='Machine_Maintenance',
            fields=[
                ('machine_maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_maintenance_amount', models.CharField(max_length=155)),
                ('machine_maintenance_date', models.DateField()),
                ('machine_maintenance_amount_paid_by', models.CharField(choices=[('Company_Owner', 'Company_Owner'), ('Office', 'Office'), ('Pinak', 'Pinak')], max_length=55)),
                ('machine_maintenance_amount_paid', models.BooleanField(default=0)),
                ('machine_maintenance_details', models.TextField(blank=True, null=True)),
                ('machine_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('machine_maintenance_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.maintenance_types')),
                ('machine_maintenance_driver_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='pinak_app.person')),
                ('machine_maintenance_person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_person', to='pinak_app.person')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Machine_Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Project_Expense',
            fields=[
                ('project_expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_expense_name', models.CharField(max_length=155)),
                ('project_expense_date', models.DateField()),
                ('project_expense_amount', models.CharField(max_length=55)),
                ('project_payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=155)),
                ('project_expense_desc', models.TextField()),
                ('bank_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.bank_details')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Project_Expense',
            },
        ),
        migrations.CreateModel(
            name='Project_Machine_Data',
            fields=[
                ('project_machine_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_machine_date', models.DateField()),
                ('project_machine_data_work_number', models.CharField(max_length=155)),
                ('project_machine_data_work_price', models.CharField(max_length=155)),
                ('project_machine_data_total_amount', models.CharField(max_length=155)),
                ('project_machine_data_work_details', models.TextField(blank=True, null=True)),
                ('project_machine_data_more_details', models.TextField(blank=True, null=True)),
                ('machine_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Machine_Data',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary_date', models.DateField(blank=True, null=True)),
                ('salary_amount', models.CharField(max_length=155)),
                ('salary_working_days', models.CharField(max_length=155)),
                ('salary_details', models.TextField(blank=True, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=55)),
                ('notification_msg', models.CharField(max_length=255)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.user')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
        migrations.CreateModel(
            name='Project_Person_Data',
            fields=[
                ('project_person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_person_date', models.DateField()),
                ('project_person_work_num', models.CharField(max_length=55)),
                ('project_person_price', models.CharField(max_length=155)),
                ('project_person_total_price', models.CharField(max_length=155)),
                ('project_person_paid_by', models.CharField(choices=[('Project_Owner', 'Project_Owner'), ('Pinak', 'Pinak'), ('Office', 'Office')], max_length=155)),
                ('project_person_payment_details', models.TextField(blank=True, null=True)),
                ('project_person_more_details', models.TextField(blank=True, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('project_machine_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_machine_data')),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Person_Data',
            },
        ),
        migrations.CreateModel(
            name='Project_Material_Data',
            fields=[
                ('project_material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_material_date', models.DateField()),
                ('project_material_work_no', models.CharField(max_length=155)),
                ('project_material_price', models.CharField(max_length=155)),
                ('project_material_total_amount', models.CharField(max_length=155)),
                ('person_material_information', models.TextField(blank=True, null=True)),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('project_material_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material')),
                ('project_material_material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_types')),
                ('project_material_work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Material_Data',
            },
        ),
        migrations.CreateModel(
            name='Project_Day_Details',
            fields=[
                ('project_day_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proejct_day_detail_date', models.DateField()),
                ('project_day_detail_total_tyres', models.CharField(blank=True, max_length=55, null=True)),
                ('project_day_detail_work_no', models.CharField(max_length=155)),
                ('project_day_detail_price', models.CharField(max_length=155)),
                ('project_day_detail_total_price', models.CharField(max_length=155)),
                ('project_day_detail_details', models.TextField(blank=True, null=True)),
                ('project_day_detail_machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('project_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('project_day_detail_work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Day_Details',
            },
        ),
    ]
