# Generated by Django 5.1.3 on 2024-12-06 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_contact_number', models.CharField(max_length=15)),
                ('company_owner_name', models.CharField(max_length=155)),
                ('company_owner_contact', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_logo', models.ImageField(upload_to='uploads/')),
                ('company_logo_icon', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'Company_Details',
            },
        ),
        migrations.CreateModel(
            name='Document_Types',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Document_Types',
            },
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language_type', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], max_length=155)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Machine_Types',
            fields=[
                ('machine_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Machine_Types',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_Types',
            fields=[
                ('maintenance_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Maintenance_Types',
            },
        ),
        migrations.CreateModel(
            name='Material_Types',
            fields=[
                ('material_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Material_Types',
            },
        ),
        migrations.CreateModel(
            name='Pay_Types',
            fields=[
                ('pay_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_type_name', models.CharField(max_length=155)),
                ('pay_type_date', models.DateField()),
            ],
            options={
                'db_table': 'Pay_Types',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=155)),
                ('person_contact_number', models.CharField(max_length=15)),
                ('person_register_date', models.DateField(auto_now_add=True)),
                ('person_status', models.BooleanField(default=1)),
                ('person_address', models.TextField(blank=True, null=True)),
                ('person_other_details', models.TextField(blank=True, null=True)),
                ('person_business_job_name', models.CharField(blank=True, max_length=255, null=True)),
                ('person_business_job_company_num', models.CharField(blank=True, max_length=15, null=True)),
                ('person_business_job_address', models.TextField(blank=True, null=True)),
                ('person_gst', models.CharField(blank=True, max_length=155, null=True)),
                ('person_types_for_project', models.CharField(choices=[('Worker', 'Worker'), ('Project', 'Project'), ('Material', 'Material'), ('Machine', 'Machine'), ('Other', 'Other')], max_length=155)),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Person_Type',
            fields=[
                ('person_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Person_Type',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=155)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_amount', models.CharField(max_length=55)),
                ('project_location', models.CharField(max_length=155)),
                ('project_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Closed', 'Closed'), ('Taken', 'Taken')], max_length=55)),
                ('project_customer_name', models.CharField(blank=True, max_length=155, null=True)),
                ('project_customer_contact', models.CharField(blank=True, max_length=155, null=True)),
                ('project_cgst', models.CharField(blank=True, max_length=55, null=True)),
                ('project_sgst', models.CharField(blank=True, max_length=55, null=True)),
                ('project_tax', models.CharField(blank=True, max_length=55, null=True)),
                ('project_discount', models.CharField(blank=True, max_length=55, null=True)),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Project_Types',
            fields=[
                ('project_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_type_name', models.CharField(max_length=155)),
                ('project_type_details', models.TextField()),
            ],
            options={
                'db_table': 'Project_Types',
            },
        ),
        migrations.CreateModel(
            name='Work_Types',
            fields=[
                ('work_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_type_name', models.CharField(max_length=155)),
                ('work_type_details', models.TextField()),
            ],
            options={
                'db_table': 'Work_Types',
            },
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(max_length=155)),
                ('machine_number_plate', models.CharField(max_length=55)),
                ('machine_register_date', models.DateField()),
                ('machine_own', models.CharField(choices=[('Company', 'Company'), ('Rented', 'Rented')], max_length=55)),
                ('machine_condition', models.CharField(blank=True, choices=[('New', 'New'), ('Second_hand', 'Second_hand')], max_length=55, null=True)),
                ('machine_working', models.BooleanField(default=1)),
                ('machine_details', models.TextField(blank=True, null=True)),
                ('machine_owner_name', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_owner_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_buy_price', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_buy_date', models.DateField(blank=True, null=True)),
                ('machine_sold_price', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_sold_out_date', models.DateField(blank=True, null=True)),
                ('machine_other_details', models.TextField(blank=True, null=True)),
                ('machine_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machine_types')),
            ],
            options={
                'db_table': 'Machines',
            },
        ),
        migrations.CreateModel(
            name='Money_Debit_Credit',
            fields=[
                ('money_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('money_credit_debit', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=155)),
                ('money_payment_mode', models.CharField(choices=[('CASH', 'CASH'), ('BANK', 'BANK')], max_length=155)),
                ('money_amount', models.CharField(max_length=155)),
                ('money_date', models.DateField()),
                ('money_sender_bank_name', models.CharField(blank=True, max_length=155, null=True)),
                ('money_sender_bank_account_no', models.CharField(blank=True, max_length=155, null=True)),
                ('money_sender_ifsc_code', models.CharField(blank=True, max_length=155, null=True)),
                ('money_sender_cheque_no', models.CharField(blank=True, max_length=155, null=True)),
                ('money_receiver_bank_name', models.CharField(blank=True, max_length=155, null=True)),
                ('money_receiver_bank_account_no', models.CharField(blank=True, max_length=155, null=True)),
                ('money_receiver_ifsc_code', models.CharField(blank=True, max_length=155, null=True)),
                ('money_payment_details', models.TextField(blank=True, null=True)),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('pay_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.pay_types')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
            ],
            options={
                'db_table': 'Money_Debit_Credit',
            },
        ),
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('bank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=155)),
                ('bank_branch', models.CharField(max_length=155)),
                ('bank_account_number', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=55)),
                ('bank_account_holder', models.CharField(blank=True, max_length=155, null=True)),
                ('bank_initial_amount', models.CharField(blank=True, max_length=155, null=True)),
                ('bank_open_closed', models.BooleanField(default=1)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
            ],
            options={
                'db_table': 'Bank_Details',
            },
        ),
        migrations.AddField(
            model_name='person',
            name='person_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type'),
        ),
        migrations.CreateModel(
            name='Machine_Maintenance',
            fields=[
                ('machine_maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_maintenance_amount', models.CharField(max_length=155)),
                ('machine_maintenance_date', models.DateField()),
                ('machine_maintenance_amount_paid_by', models.CharField(choices=[('Company_Owner', 'Company_Owner'), ('Office', 'Office'), ('Pinak', 'Pinak')], max_length=55)),
                ('machine_maintenance_amount_paid', models.BooleanField(default=0)),
                ('machine_maintenance_details', models.TextField(blank=True, null=True)),
                ('machine_maintenance_driver_name', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_maintenance_driver_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_maintenance_repair_person', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_maintenance_repair_person_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('machine_maintenance_other_details', models.TextField(blank=True, null=True)),
                ('machine_maintenance_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.maintenance_types')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Machine_Maintenance',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='project_types_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_types'),
        ),
        migrations.CreateModel(
            name='Project_With_Person_N_Machine',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('machine_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('person_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Project_With_Person_N_Machine',
            },
        ),
        migrations.CreateModel(
            name='Project_Machine_Data',
            fields=[
                ('project_machine_data_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_machine_date', models.DateField()),
                ('project_machine_data_work_number', models.CharField(max_length=155)),
                ('project_machine_data_work_price', models.CharField(max_length=155)),
                ('project_machine_data_total_amount', models.CharField(max_length=155)),
                ('project_machine_data_work_details', models.TextField(blank=True, null=True)),
                ('project_machine_data_more_details', models.TextField(blank=True, null=True)),
                ('machine_project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_with_person_n_machine')),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Machine_Data',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('salary_amount', models.CharField(max_length=155)),
                ('salary_working_days', models.CharField(max_length=155)),
                ('salary_details', models.TextField(blank=True, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Project_Person_Data',
            fields=[
                ('project_person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_person_date', models.DateField()),
                ('project_person_work_num', models.CharField(max_length=55)),
                ('project_person_price', models.CharField(max_length=155)),
                ('project_person_total_price', models.CharField(max_length=155)),
                ('project_person_paid_by', models.CharField(choices=[('Project_Owner', 'Project_Owner'), ('Pinak', 'Pinak'), ('Office', 'Office')], max_length=155)),
                ('project_person_payment_details', models.TextField(blank=True, null=True)),
                ('project_person_more_details', models.TextField(blank=True, null=True)),
                ('project_machine_data_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_machine_data')),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_with_person_n_machine')),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Person_Data',
            },
        ),
    ]
