# Generated by Django 5.1.3 on 2024-11-25 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Details',
            fields=[
                ('bank_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=155)),
                ('bank_branch', models.CharField(max_length=155)),
                ('bank_account_number', models.IntegerField()),
                ('bank_ifsc_code', models.CharField(max_length=55)),
                ('bank_account_holder', models.CharField(max_length=155)),
                ('bank_open_closed', models.BooleanField(default=1)),
            ],
            options={
                'db_table': 'Bank_Details',
            },
        ),
        migrations.CreateModel(
            name='Company_Details',
            fields=[
                ('company_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_contact_number', models.CharField(max_length=15)),
                ('company_owner_name', models.CharField(max_length=155)),
                ('company_owner_contact', models.CharField(max_length=15)),
                ('company_address', models.TextField()),
                ('company_logo', models.ImageField(upload_to='uploads/')),
                ('company_logo_icon', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'Company_Details',
            },
        ),
        migrations.CreateModel(
            name='Machine_Types',
            fields=[
                ('machine_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Machine_Types',
            },
        ),
        migrations.CreateModel(
            name='Maintenance_Types',
            fields=[
                ('maintenance_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('maintenance_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Maintenance_Types',
            },
        ),
        migrations.CreateModel(
            name='Material_Types',
            fields=[
                ('material_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Material_Types',
            },
        ),
        migrations.CreateModel(
            name='Pay_Types',
            fields=[
                ('pay_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pay_type_name', models.CharField(max_length=155)),
                ('pay_type_date', models.DateField()),
            ],
            options={
                'db_table': 'Pay_Types',
            },
        ),
        migrations.CreateModel(
            name='Person_Type',
            fields=[
                ('person_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Person_Type',
            },
        ),
        migrations.CreateModel(
            name='Project_Types',
            fields=[
                ('project_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_type_name', models.CharField(max_length=155)),
                ('project_type_details', models.TextField()),
            ],
            options={
                'db_table': 'Project_Types',
            },
        ),
        migrations.CreateModel(
            name='Work_Types',
            fields=[
                ('work_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_type_name', models.CharField(max_length=155)),
                ('work_type_details', models.TextField()),
            ],
            options={
                'db_table': 'Work_Types',
            },
        ),
        migrations.CreateModel(
            name='Company_Machines',
            fields=[
                ('machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_owner', models.CharField(max_length=155)),
                ('machine_buy_date', models.DateField()),
                ('machine_condition', models.CharField(choices=[('New', 'New'), ('Second_hand', 'Second_hand')], max_length=55)),
                ('machine_number_plate', models.CharField(max_length=55)),
                ('machine_details', models.TextField()),
                ('machine_contact_number', models.CharField(max_length=15)),
                ('machine_sold_out_date', models.DateField(blank=True, null=True)),
                ('machine_sold_price', models.CharField(blank=True, max_length=155, null=True)),
                ('machine_working', models.BooleanField(default=1)),
                ('machine_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machine_types')),
            ],
            options={
                'db_table': 'Company_Machines',
            },
        ),
        migrations.CreateModel(
            name='Machine_Maintenance',
            fields=[
                ('machine_maintenance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('machine_maintenance_amount', models.CharField(max_length=155)),
                ('machine_maintenance_date', models.DateField()),
                ('machine_maintenance_amount_paid', models.BooleanField(default=0)),
                ('machine_maintenance_amount_paid_by', models.CharField(choices=[('Machine_Owner', 'Machine_Owner'), ('Pinak_Enterprise', 'Pinak_Enterprise'), ('Pinak', 'Pinak')], max_length=55)),
                ('machine_maintenance_person', models.CharField(max_length=155)),
                ('machine_maintenance_contact', models.CharField(max_length=15)),
                ('machine_maintenance_driver', models.CharField(max_length=155)),
                ('machine_maintenance_details', models.TextField()),
                ('machine_maintenance_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.maintenance_types')),
            ],
            options={
                'db_table': 'Machine_Maintenance',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('person_name', models.CharField(max_length=155)),
                ('person_contact_number', models.CharField(max_length=15)),
                ('person_work_type', models.CharField(choices=[('Worker', 'Worker'), ('Project', 'Project'), ('Material', 'Material'), ('Machine', 'Machine'), ('Bhatthu', 'Bhatthu'), ('Other', 'Other')], max_length=155)),
                ('person_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type')),
            ],
            options={
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=155)),
                ('project_start_date', models.DateField(blank=True, null=True)),
                ('project_end_date', models.DateField(blank=True, null=True)),
                ('project_amount', models.CharField(blank=True, max_length=55, null=True)),
                ('project_location', models.CharField(blank=True, max_length=155, null=True)),
                ('project_company_name', models.CharField(max_length=155)),
                ('project_person_name', models.CharField(max_length=155)),
                ('project_status', models.CharField(choices=[('Ongoing', 'Ongoing'), ('Closed', 'Closed'), ('Taken', 'Taken')], max_length=55)),
                ('project_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_types')),
            ],
            options={
                'db_table': 'Project',
            },
        ),
        migrations.CreateModel(
            name='Materials',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_owner_name', models.CharField(max_length=155)),
                ('material_used_date', models.DateField(blank=True, null=True)),
                ('material_work_number', models.CharField(max_length=55)),
                ('material_work_amount', models.CharField(max_length=55)),
                ('material_work_total_amount', models.CharField(max_length=55)),
                ('total_material_amount', models.CharField(max_length=55)),
                ('material_desc', models.TextField(blank=True, null=True)),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_types')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='Working_Machines',
            fields=[
                ('working_machine_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('working_machine_name', models.CharField(max_length=155)),
                ('working_machine_owner_name', models.CharField(max_length=155)),
                ('working_machine_owner_contact', models.CharField(max_length=15)),
                ('working_machine_plate_number', models.CharField(max_length=55)),
                ('working_machine_start_date', models.DateField(blank=True, null=True)),
                ('working_machine_end_date', models.DateField(blank=True, null=True)),
                ('working_machine_ownership', models.CharField(choices=[('Rent_Machine', 'Rent_Machine'), ('Own_Machine', 'Own_Machine'), ('Company_Machine', 'Company_Machine')], max_length=55)),
                ('working_machine_details', models.TextField()),
                ('working_machine_rented_amount', models.CharField(blank=True, max_length=55, null=True)),
                ('machine_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machine_types')),
            ],
            options={
                'db_table': 'Working_Machines',
            },
        ),
        migrations.CreateModel(
            name='Person_Work_Machine',
            fields=[
                ('pwm_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('pwm_machine_name', models.CharField(max_length=155)),
                ('pwm_machine_owner_name', models.CharField(max_length=155)),
                ('pwm_machine_owner_number', models.CharField(max_length=15)),
                ('pwm_person_joining_date', models.DateField(blank=True, null=True)),
                ('pwm_person_contact_number', models.CharField(max_length=15)),
                ('pwm_person_payment_by', models.CharField(choices=[('Company_Owner', 'Company_Owner'), ('Pinak_Enterprise', 'Pinak_Enterprise'), ('Pinak', 'Pinak')], max_length=155)),
                ('pwm_person_payment_desc', models.TextField(blank=True, null=True)),
                ('pwm_work_number', models.CharField(max_length=55)),
                ('pwm_work_amount', models.CharField(max_length=55)),
                ('pwm_total_amount', models.CharField(max_length=55)),
                ('pwm_work_desc', models.TextField(blank=True, null=True)),
                ('person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('person_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
                ('project_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_types')),
                ('work_types_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
                ('working_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.working_machines')),
            ],
            options={
                'db_table': 'Person_Work_Machine',
            },
        ),
    ]
