# Generated by Django 5.1.3 on 2024-12-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_day_details',
            name='proejct_day_detail_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
