# Generated by Django 5.1.3 on 2024-12-13 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Expense',
            fields=[
                ('project_expense_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_expense_name', models.CharField(max_length=155)),
                ('project_expense_date', models.DateField()),
                ('project_expense_amount', models.CharField(max_length=55)),
                ('project_payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Bank', 'Bank')], max_length=155)),
                ('project_expense_desc', models.TextField()),
                ('bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.bank_details')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project')),
            ],
            options={
                'db_table': 'Project_Expense',
            },
        ),
    ]
