# Generated by Django 5.1.3 on 2024-12-08 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_types_for_project',
            field=models.CharField(blank=True, choices=[('Worker', 'Worker'), ('Project', 'Project'), ('Material', 'Material'), ('Machine', 'Machine'), ('Other', 'Other')], max_length=155, null=True),
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('material_status', models.BooleanField(default=1)),
                ('material_details', models.TextField(blank=True, null=True)),
                ('material_person_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_types')),
            ],
            options={
                'db_table': 'Material',
            },
        ),
        migrations.CreateModel(
            name='Project_Day_Details',
            fields=[
                ('project_day_detail_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('proejct_day_detail_date', models.DateField()),
                ('project_day_detail_work_no', models.CharField(max_length=155)),
                ('project_day_detail_price', models.CharField(max_length=155)),
                ('project_day_detail_total_price', models.CharField(max_length=155)),
                ('project_day_detail_details', models.TextField(blank=True, null=True)),
                ('project_day_detail_machine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines')),
                ('project_day_detail_work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Day_Details',
            },
        ),
        migrations.CreateModel(
            name='Project_Material_Data',
            fields=[
                ('project_material_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('project_material_date', models.DateField()),
                ('project_material_work_no', models.CharField(max_length=155)),
                ('project_material_price', models.CharField(max_length=155)),
                ('project_material_total_amount', models.CharField(max_length=155)),
                ('project_material_agent', models.BooleanField(default=0)),
                ('person_material_agent_amount', models.CharField(blank=True, max_length=155, null=True)),
                ('person_material_information', models.TextField(blank=True, null=True)),
                ('project_material_agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person')),
                ('project_material_material_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material')),
                ('project_material_material_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_types')),
                ('project_material_work_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types')),
            ],
            options={
                'db_table': 'Project_Material_Data',
            },
        ),
    ]
