# Generated by Django 5.1.3 on 2024-12-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salary',
            name='salary_date',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
