# Generated by Django 5.1.5 on 2025-02-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_material_data',
            name='project_material_material_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.material_owner_data'),
        ),
    ]
