# Generated by Django 5.1.3 on 2024-12-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='machine_km',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
