# Generated by Django 5.1.3 on 2024-11-25 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('language_type', models.CharField(choices=[('English', 'English'), ('Gujarati', 'Gujarati')], max_length=155)),
            ],
            options={
                'db_table': 'Languages',
            },
        ),
    ]
