# Generated by Django 5.1.3 on 2024-12-08 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money_debit_credit',
            name='receiver_bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver_bank_id', to='pinak_app.bank_details'),
        ),
        migrations.AlterField(
            model_name='money_debit_credit',
            name='sender_bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_bank_id', to='pinak_app.bank_details'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person_type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='person_types_for_project',
            field=models.CharField(blank=True, choices=[('Worker', 'Worker'), ('Project', 'Project'), ('Material', 'Material'), ('Machine', 'Machine'), ('Other', 'Other')], max_length=155, null=True),
        ),
    ]
