# Generated by Django 5.1.3 on 2024-12-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_project_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_types',
            name='project_type_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
