# Generated by Django 5.1.3 on 2024-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_salary_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
