# Generated by Django 5.1.3 on 2024-12-16 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_project_expense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machines',
            name='machine_owner_contact',
        ),
        migrations.RemoveField(
            model_name='machines',
            name='machine_owner_name',
        ),
        migrations.AddField(
            model_name='machines',
            name='machine_owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person'),
        ),
    ]
