# Generated by Django 5.1.3 on 2024-12-08 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_alter_money_debit_credit_receiver_bank_id_and_more'),
        ('pinak_app', '0002_alter_person_person_type_id_and_more'),
    ]

    operations = [
    ]
