# Generated by Django 5.1.3 on 2024-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_alter_project_day_details_proejct_day_detail_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_maintenance',
            name='machine_maintenance_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
