# Generated by Django 5.1.3 on 2024-12-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0003_merge_20241209_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine_maintenance',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
    ]
