# Generated by Django 5.1.3 on 2024-11-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0003_document_types_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_details',
            name='bank_account_number',
            field=models.CharField(max_length=100),
        ),
    ]
