# Generated by Django 5.1.3 on 2024-12-23 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0003_alter_machine_maintenance_machine_maintenance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_machine_data',
            name='project_machine_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
