# Generated by Django 5.1.5 on 2025-02-23 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0003_remove_work_types_work_type_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='machine_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines'),
        ),
        migrations.AddField(
            model_name='documents',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
    ]
