# Generated by Django 5.1.3 on 2024-12-08 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0004_alter_machine_maintenance_project_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_maintenance',
            name='machine_maintenance_other_details',
        ),
    ]
