# Generated by Django 5.1.3 on 2024-12-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0004_remove_pay_types_pay_type_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work_types',
            name='work_type_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
