# Generated by Django 5.1.3 on 2024-12-23 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0002_machines_machine_km'),
        ('pinak_app', '0004_alter_project_machine_data_project_machine_date'),
    ]

    operations = [
    ]
