# Generated by Django 5.1.3 on 2024-12-09 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0005_remove_machine_maintenance_machine_maintenance_other_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_person_data',
            name='person_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person'),
        ),
        migrations.AlterField(
            model_name='project_machine_data',
            name='machine_project_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines'),
        ),
        migrations.DeleteModel(
            name='Project_With_Person_N_Machine',
        ),
    ]
