# Generated by Django 5.1.3 on 2024-12-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0003_remove_machines_machine_owner_contact_and_more'),
        ('pinak_app', '0005_alter_work_types_work_type_details'),
    ]

    operations = [
    ]
