# Generated by Django 5.1.3 on 2024-12-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0005_merge_20241223_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='machine_register_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
