# Generated by Django 5.1.3 on 2024-12-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0005_alter_project_expense_project_expense_date'),
        ('pinak_app', '0006_alter_machines_machine_register_date'),
    ]

    operations = [
    ]
