# Generated by Django 5.1.5 on 2025-03-06 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0006_alter_project_person_data_person_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_machine_data',
            name='project_machine_data_km',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
