# Generated by Django 5.1.3 on 2024-12-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0006_alter_project_person_data_person_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_customer_contact',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_customer_name',
        ),
        migrations.AddField(
            model_name='project',
            name='project_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person'),
        ),
    ]
