# Generated by Django 5.1.3 on 2024-12-16 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0006_merge_20241216_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='machine_rented_work_price',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='machines',
            name='machine_rented_work_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.work_types'),
        ),
    ]
