# Generated by Django 5.1.3 on 2024-12-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0007_remove_project_project_customer_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='person_salary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
