# Generated by Django 5.1.3 on 2024-12-23 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0007_merge_20241223_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_material_data',
            name='project_material_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project_person_data',
            name='project_machine_data_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project_machine_data'),
        ),
        migrations.AlterField(
            model_name='project_person_data',
            name='project_person_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
