# Generated by Django 5.1.3 on 2024-12-16 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0007_machines_machine_rented_work_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine_maintenance',
            name='machine_maintenance_driver_contact',
        ),
        migrations.RemoveField(
            model_name='machine_maintenance',
            name='machine_maintenance_driver_name',
        ),
        migrations.AddField(
            model_name='machine_maintenance',
            name='machine_maintenance_driver_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver', to='pinak_app.person'),
        ),
        migrations.AlterField(
            model_name='machine_maintenance',
            name='machine_maintenance_person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repair_person', to='pinak_app.person'),
        ),
    ]
