# Generated by Django 5.1.5 on 2025-03-06 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0007_project_machine_data_project_machine_data_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Office_kharch_Types',
            fields=[
                ('office_kharch_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('office_kharch_type_name', models.CharField(max_length=155)),
            ],
            options={
                'db_table': 'Office_kharch_Types',
            },
        ),
    ]
