# Generated by Django 5.1.3 on 2024-12-17 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0008_remove_machine_maintenance_machine_maintenance_driver_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=155)),
                ('user_email', models.EmailField(max_length=254)),
                ('user_contact', models.CharField(max_length=15)),
                ('user_password', models.CharField(max_length=55)),
                ('user_otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.AlterField(
            model_name='machines',
            name='machine_own',
            field=models.CharField(choices=[('Company', 'Company'), ('Rented_fixedprice', 'Rented_fixedprice'), ('Rented_variableprice', 'Rented_variableprice')], max_length=55),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('notification_title', models.CharField(max_length=55)),
                ('notification_msg', models.CharField(max_length=255)),
                ('notification_date', models.DateField(auto_now_add=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pinak_app.user')),
            ],
            options={
                'db_table': 'Notification',
            },
        ),
    ]
