# Generated by Django 5.1.3 on 2024-12-23 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0008_alter_project_material_data_project_material_date_and_more'),
        ('pinak_app', '0008_project_project_investor_and_more'),
    ]

    operations = [
    ]
