# Generated by Django 5.1.5 on 2025-03-24 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0008_office_kharch_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_debit_credit',
            name='office_kharch_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.office_kharch_types'),
        ),
    ]
