# Generated by Django 5.1.3 on 2024-12-17 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0008_remove_machine_maintenance_machine_maintenance_driver_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='machine_own',
            field=models.CharField(choices=[('Company', 'Company'), ('Rented_fixedprice', 'Rented_fixedprice'), ('Rented_variableprice', 'Rented_variableprice')], max_length=55),
        ),
    ]
