# Generated by Django 5.1.3 on 2024-12-11 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0008_person_person_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='money_debit_credit',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
    ]
