# Generated by Django 5.1.3 on 2024-12-17 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0009_alter_machines_machine_own'),
        ('pinak_app', '0009_user_alter_machines_machine_own_notification'),
    ]

    operations = [
    ]
