# Generated by Django 5.1.3 on 2024-12-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0009_merge_20241224_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_cash',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
