# Generated by Django 5.1.3 on 2024-12-11 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0009_money_debit_credit_project_id'),
        ('pinak_app', '0009_remove_machine_maintenance_machine_maintenance_repair_person_and_more'),
    ]

    operations = [
    ]
