# Generated by Django 5.1.3 on 2024-12-23 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0009_merge_20241224_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='diary',
            fields=[
                ('diary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('diary_text', models.TextField()),
            ],
            options={
                'db_table': 'diary',
            },
        ),
    ]
