# Generated by Django 5.1.3 on 2024-12-11 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0010_merge_20241212_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine_maintenance',
            name='machine_machine_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.machines'),
            preserve_default=False,
        ),
    ]
