# Generated by Django 5.1.3 on 2024-12-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0010_merge_20241218_0202'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document_Dates',
            fields=[
                ('dd_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dd_date_name', models.CharField(max_length=200)),
                ('dd_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Document_Dates',
            },
        ),
    ]
