# Generated by Django 5.1.3 on 2024-12-12 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0011_machine_maintenance_machine_machine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_day_details',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
        migrations.AddField(
            model_name='project_machine_data',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
        migrations.AddField(
            model_name='project_material_data',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
        migrations.AddField(
            model_name='project_person_data',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.project'),
        ),
    ]
