# Generated by Django 5.1.3 on 2024-12-17 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0011_document_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='document_dates',
            name='dd_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.documents'),
        ),
    ]
