# Generated by Django 5.1.3 on 2024-12-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0010_merge_20241218_0120'),
        ('pinak_app', '0012_document_dates_dd_document'),
    ]

    operations = [
    ]
