# Generated by Django 5.1.3 on 2024-12-18 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0013_merge_20241219_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_details',
            name='company_bank_account',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_logo_icon',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
