# Generated by Django 5.1.3 on 2024-12-13 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0013_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='person_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.person'),
        ),
    ]
