# Generated by Django 5.1.3 on 2024-12-19 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0015_bank_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='material_buy_location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
