# Generated by Django 5.1.3 on 2024-12-19 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0016_material_material_buy_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_agent',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='project_agent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_name', to='pinak_app.person'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_agent_type',
            field=models.CharField(blank=True, choices=[('Percentage', 'Percentage'), ('Fixed', 'Fixed')], max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_owner_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='pinak_app.person'),
        ),
    ]
