# Generated by Django 5.1.3 on 2024-12-19 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0017_project_project_agent_project_project_agent_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_agent_final_amount',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_agent_fixed_amount',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_agent_percentage',
            field=models.CharField(blank=True, max_length=155, null=True),
        ),
    ]
