# Generated by Django 5.1.3 on 2024-12-19 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0018_project_project_agent_final_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_agent_final_amount',
            new_name='project_final_amount',
        ),
    ]
