# Generated by Django 5.1.3 on 2024-12-20 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0019_rename_project_agent_final_amount_project_project_final_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='language',
            fields=[
                ('language_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gujarati', models.CharField(max_length=200)),
                ('english', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'language',
            },
        ),
    ]
