# Generated by Django 5.1.3 on 2024-12-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0020_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='settings',
            fields=[
                ('settings_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('settings_field_name', models.CharField(max_length=200)),
                ('settings_field_value', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'settings',
            },
        ),
    ]
