# Generated by Django 5.1.3 on 2024-12-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0021_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='settings',
            new_name='Settingsss',
        ),
        migrations.AlterModelTable(
            name='settingsss',
            table='Settingsss',
        ),
    ]
