# Generated by Django 5.1.3 on 2024-12-20 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0022_rename_settings_settingsss_alter_settingsss_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project_expense',
            name='bank_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pinak_app.bank_details'),
        ),
    ]
