# Generated by Django 5.1.3 on 2024-12-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0024_alter_project_day_details_project_day_detail_machine_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_amount',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_end_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
