# Generated by Django 5.1.3 on 2024-12-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinak_app', '0025_alter_project_project_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_day_details',
            name='project_day_detail_total_tyres',
            field=models.CharField(blank=True, max_length=55, null=True),
        ),
    ]
